workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        provisioning_type: development
    scripts:
      - flutter pub get
      - flutter build ipa --debug --export-method=development
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - zjjdhbhx@gmail.com
