workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --debug --no-codesign --export-method=development
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - zjjdhbhx@gmail.com
